[[SCS]]
arch = "aarch64"
git-tree-sha1 = "25e639562413e76fba605537ffe02f5aad1fdc22"
os = "macos"

    [[SCS.download]]
    sha256 = "e925a4b5e1061d093e8abfc44b109010666d7b161fa1aa94e14afd91bb6e436a"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.aarch64-apple-darwin.tar.gz"
[[SCS]]
arch = "aarch64"
git-tree-sha1 = "d1a9145d5b673d9db82634cfae93547897174a62"
libc = "glibc"
os = "linux"

    [[SCS.download]]
    sha256 = "faeb9671b1f1f0284f1c98c0f306660f949178ecf8f90229c392a6e0761aa8ba"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.aarch64-linux-gnu.tar.gz"
[[SCS]]
arch = "aarch64"
git-tree-sha1 = "5820003b5829b0be3159e67f9a0ae232dfecbda5"
libc = "musl"
os = "linux"

    [[SCS.download]]
    sha256 = "f694d4b7dae6fe59c06dff8f5c1cbf6820af4e3d8542fe0f56ccee6ef8033471"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.aarch64-linux-musl.tar.gz"
[[SCS]]
arch = "aarch64"
git-tree-sha1 = "be0ae565950c39d00eb718551e6f0ca7248411c5"
os = "freebsd"

    [[SCS.download]]
    sha256 = "3229c6fa1588f33494d507ba4f93ddcb01f45f3c4ad8e9d2a76b6cc7544e3734"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.aarch64-unknown-freebsd.tar.gz"
[[SCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e623875af248890ae4e1125dec94f8a5975ebc7f"
libc = "glibc"
os = "linux"

    [[SCS.download]]
    sha256 = "8eeddc38281b28bcbfb72c78183ee9f966f1a1a9665c4cfda4ceb36cdf4c88f0"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.armv6l-linux-gnueabihf.tar.gz"
[[SCS]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0bd8e4ddbfdcdd034cd9ed49d2c2ae94cf5decc3"
libc = "musl"
os = "linux"

    [[SCS.download]]
    sha256 = "d03b7d74eeeaabb5725c2f97be36726c6fad42d70836f358b6b18e8131c2980a"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.armv6l-linux-musleabihf.tar.gz"
[[SCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "12f6396e4bf40dd9362cafa1bb3c825f23f33d25"
libc = "glibc"
os = "linux"

    [[SCS.download]]
    sha256 = "be10c5f711aac1d495deb04309ade588f4182e783bc26d347fcde3e169669cac"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.armv7l-linux-gnueabihf.tar.gz"
[[SCS]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d1eb8289f39393c7732cca11336aef190f1de317"
libc = "musl"
os = "linux"

    [[SCS.download]]
    sha256 = "652cb3595cb2c51fb587b36e552d10b78db35031d26273da37b5de1fd6c22987"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.armv7l-linux-musleabihf.tar.gz"
[[SCS]]
arch = "i686"
git-tree-sha1 = "3f8b053df1ddcd91fd9029f2e862b648424594f6"
libc = "glibc"
os = "linux"

    [[SCS.download]]
    sha256 = "c2894b50daad6846d7bdb75bb0e559c01a0b3768c0b5134a3c1e71b0df6f1032"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.i686-linux-gnu.tar.gz"
[[SCS]]
arch = "i686"
git-tree-sha1 = "843f7d827cf0ee52ac03a9d200aed6ad45cddd80"
libc = "musl"
os = "linux"

    [[SCS.download]]
    sha256 = "286b3d96d168e7ba7e2aa5910e1ff0bfc832403de387e01a772bf1b6c4ecff00"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.i686-linux-musl.tar.gz"
[[SCS]]
arch = "i686"
git-tree-sha1 = "97c4dafeba923e67d0affa50751820b95d8dce89"
os = "windows"

    [[SCS.download]]
    sha256 = "d539d83a276bb5635db9ae210d822a189ec682bfad19f9378e00e48c76b37655"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.i686-w64-mingw32.tar.gz"
[[SCS]]
arch = "powerpc64le"
git-tree-sha1 = "7579c8748996260a63a151724531eedf9a3a780e"
libc = "glibc"
os = "linux"

    [[SCS.download]]
    sha256 = "2fc89bbe4eec79998854ca347f98c33ba972edc8e149337ea696e036a7d5f0d0"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.powerpc64le-linux-gnu.tar.gz"
[[SCS]]
arch = "riscv64"
git-tree-sha1 = "d52ac4be305a1acce910d133f0f23ca006c0e12d"
libc = "glibc"
os = "linux"

    [[SCS.download]]
    sha256 = "f3f7757ac4e0c2e4a0b92ee3265d996a04c31d918bd19b2fb98a6e4badae0ef4"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.riscv64-linux-gnu.tar.gz"
[[SCS]]
arch = "x86_64"
git-tree-sha1 = "3a71a9fd5a47006b1b0afcfc9f96508a3521f180"
os = "macos"

    [[SCS.download]]
    sha256 = "1206d83b3f65503b5274180b628ae31dbd1187d365c52d7b4eb08363037c7a74"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.x86_64-apple-darwin.tar.gz"
[[SCS]]
arch = "x86_64"
git-tree-sha1 = "efc4f95dcbbbbfe10d38e27491b75112fc08bc47"
libc = "glibc"
os = "linux"

    [[SCS.download]]
    sha256 = "3dc9e85cb0b46b3de00e0e2ffee86b8974d4206bc502d315a371b7026ec05f45"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.x86_64-linux-gnu.tar.gz"
[[SCS]]
arch = "x86_64"
git-tree-sha1 = "b303233f513b4f1ad5e214cd6cb24409ec7492d0"
libc = "musl"
os = "linux"

    [[SCS.download]]
    sha256 = "2637139c8fda73a7e25f546fbd7f0abca1cf693d74314e41a827a3f0bc03e685"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.x86_64-linux-musl.tar.gz"
[[SCS]]
arch = "x86_64"
git-tree-sha1 = "7e850689949d869d95e32b696bfa8f2e42d3cb78"
os = "freebsd"

    [[SCS.download]]
    sha256 = "69a1b2541d9b83e4f39ef715ff738ee85d4d3026a399ee2fc93d0b29b378b732"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.x86_64-unknown-freebsd.tar.gz"
[[SCS]]
arch = "x86_64"
git-tree-sha1 = "bfcda62430e0a2e98f509b6906335f61caf2c4b2"
os = "windows"

    [[SCS.download]]
    sha256 = "04403e2d76675e91b1ee0bbb968d305542a4df7d4f4ee2a6d11aa33180471412"
    url = "https://github.com/JuliaBinaryWrappers/SCS_jll.jl/releases/download/SCS-v300.200.1100+0/SCS.v300.200.1100.x86_64-w64-mingw32.tar.gz"
